server:
  port: 8761

spring:
  application:
    name: discoveryservice
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://192.168.192.2:30088} # VPN

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false